-- MySQL Script generated by MySQL Workbench
-- Wed Apr 29 00:49:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jpa-daily
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jpa-daily` ;

-- -----------------------------------------------------
-- Schema jpa-daily
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jpa-daily` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
SHOW WARNINGS;
USE `jpa-daily` ;

-- -----------------------------------------------------
-- Table `jpa-daily`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jpa-daily`.`person` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jpa-daily`.`person` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_person_name` (`name` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jpa-daily`.`diary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jpa-daily`.`diary` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jpa-daily`.`diary` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person` BIGINT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_diary_person_date` (`person` ASC, `date` ASC),
  INDEX `idx_diary_date` (`date` ASC),
  CONSTRAINT `fk_diary_pk_person`
    FOREIGN KEY (`person`)
    REFERENCES `jpa-daily`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jpa-daily`.`person2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jpa-daily`.`person2` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jpa-daily`.`person2` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_person2_name` (`name` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jpa-daily`.`diary2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jpa-daily`.`diary2` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jpa-daily`.`diary2` (
  `person` BIGINT UNSIGNED NOT NULL,
  `date` CHAR(9) NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`person`, `date`),
  CONSTRAINT `fk_diary2_pk_person2`
    FOREIGN KEY (`person`)
    REFERENCES `jpa-daily`.`person2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
